# Generated by Django 5.1.4 on 2025-01-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Article',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
