# Generated by Django 5.1.4 on 2025-01-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Article',
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
