# Generated by Django 5.1.4 on 2025-01-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_sku_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Article',
            field=models.IntegerField(blank=True),
        ),
    ]
