# Generated by Django 5.1.4 on 2025-01-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(blank=True, max_length=100, unique=True),
        ),
    ]
